/**
 * Maps FAQ database slugs to i18n translation keys.
 * Category slugs map to faq.cat_* keys.
 * Article slugs map to faq.q_* keys.
 */

export const CATEGORY_SLUG_TO_KEY = {
  'getting-started':       'cat_gettingStarted',
  'nutrition-tracking':    'cat_nutritionTracking',
  'fitness-workouts':      'cat_fitnessWorkouts',
  'goals-progress':        'cat_goalsProgress',
  'medications-health':    'cat_medicationsHealth',
  'ai-coach':              'cat_aiCoach',
  'account-settings':      'cat_accountSettings',
  'subscription-billing':  'cat_subscriptionBilling',
  'troubleshooting':       'cat_troubleshooting',
}

export const ARTICLE_SLUG_TO_KEY = {
  'how-do-i-set-up-my-yfit-profile-for-the-first-time':                          'q_setupProfile',
  'what-does-yfit-actually-track':                                                 'q_whatDoesYfitTrack',
  'how-do-i-navigate-between-pages-in-the-app':                                   'q_navigateBetweenPages',
  'is-my-data-private-and-secure':                                                 'q_dataPrivacy',
  'can-i-use-yfit-on-both-my-phone-and-a-web-browser':                            'q_phoneAndBrowser',
  'how-do-i-change-my-units-between-metric-and-imperial':                         'q_changeUnits',
  'what-is-the-beta-programme-and-how-do-i-join':                                 'q_betaProgramme',
  'how-do-i-log-out-of-yfit':                                                     'q_logOut',
  'how-do-i-delete-my-account':                                                   'q_deleteAccount',
  'what-should-i-do-first-after-signing-up':                                      'q_firstAfterSignup',
  'how-do-i-log-a-meal-or-food-item':                                             'q_logMeal',
  'how-does-the-barcode-scanner-work':                                             'q_barcodeScanner',
  'how-do-i-create-a-custom-food':                                                 'q_createCustomFood',
  'what-is-the-my-foods-tab':                                                      'q_myFoodsTab',
  'how-do-i-set-my-calorie-and-macro-targets':                                    'q_setCalorieTargets',
  'what-is-tdee-and-how-is-it-calculated':                                        'q_whatIsTdee',
  'can-i-log-water-intake':                                                        'q_logWater',
  'why-are-my-calories-showing-differently-than-expected':                        'q_caloriesShowingDifferently',
  'how-do-i-edit-or-delete-a-food-i-already-logged':                             'q_editDeleteFood',
  'what-food-databases-does-yfit-use':                                             'q_foodDatabases',
  'how-do-i-log-a-workout':                                                        'q_logWorkout',
  'what-is-form-analysis-and-how-does-it-work':                                   'q_formAnalysis',
  'what-exercises-are-available-in-the-workout-library':                          'q_exercisesAvailable',
  'how-do-i-create-a-custom-workout-plan':                                        'q_createWorkoutPlan',
  'what-does-the-strength-stats-tab-show':                                        'q_strengthStatsTab',
  'how-do-i-track-cardio-workouts':                                               'q_trackCardio',
  'can-i-see-my-workout-history':                                                  'q_workoutHistory',
  'what-is-the-difference-between-a-workout-session-and-a-worko':                'q_sessionVsPlan',
  'how-do-i-use-progressive-overload-tracking':                                   'q_progressiveOverload',
  'how-is-my-workout-compliance-tracked':                                          'q_workoutCompliance',
  'how-do-i-set-my-fitness-goals':                                                 'q_setFitnessGoals',
  'what-is-body-recomposition':                                                    'q_bodyRecomposition',
  'how-do-i-track-my-weight-and-body-fat':                                        'q_trackWeightBodyFat',
  'how-do-i-track-body-measurements':                                              'q_trackBodyMeasurements',
  'what-does-the-progress-page-show':                                              'q_progressPageShows',
  'what-is-the-day-streak-on-my-dashboard':                                       'q_dayStreak',
  'how-do-i-set-body-measurement-goals':                                           'q_bodyMeasurementGoals',
  'how-accurate-are-the-calorie-and-macro-calculations':                          'q_calorieMacroAccuracy',
  'what-is-the-predictions-page':                                                  'q_predictionsPage',
  'how-does-the-activity-level-setting-affect-my-calorie-target':                'q_activityLevelCalories',
  'how-do-i-add-a-medication-to-track':                                           'q_addMedication',
  'how-do-medication-reminders-work':                                              'q_medicationReminders',
  'can-i-track-supplements-as-well-as-medications':                               'q_trackSupplements',
  'how-do-i-mark-a-dose-as-taken':                                                'q_markDoseTaken',
  'can-i-see-my-medication-history':                                               'q_medicationHistory',
  'how-do-i-edit-or-delete-a-medication':                                         'q_editDeleteMedication',
  'does-yfit-provide-medical-advice':                                              'q_medicalAdvice',
  'can-i-set-different-schedules-for-different-days':                             'q_differentSchedules',
  'what-health-metrics-can-i-track-beyond-medications':                           'q_healthMetrics',
  'how-do-i-log-my-daily-steps':                                                   'q_logDailySteps',
  'what-can-the-ai-coach-help-me-with':                                            'q_aiCoachHelp',
  'how-do-i-start-a-conversation-with-the-ai-coach':                              'q_startConversation',
  'does-the-ai-coach-remember-my-previous-conversations':                         'q_aiRemembersPrevious',
  'is-the-ai-coach-advice-safe-to-follow':                                        'q_aiSafeToFollow',
  'can-the-ai-coach-create-a-workout-plan-for-me':                                'q_aiCreateWorkoutPlan',
  'can-the-ai-coach-help-with-meal-planning':                                     'q_aiMealPlanning',
  'why-is-the-ai-coach-slow-to-respond-sometimes':                                'q_aiSlowToRespond',
  'how-do-i-give-feedback-on-an-ai-response':                                     'q_feedbackOnAiResponse',
  'what-is-the-faq-tab-in-the-ai-coach-section':                                  'q_faqTabInAiCoach',
  'does-the-ai-coach-use-my-personal-data':                                       'q_aiUsesPersonalData',
  'how-do-i-change-my-email-address-or-password':                                 'q_changeEmailPassword',
  'how-do-i-turn-on-or-off-notifications':                                        'q_turnOnOffNotifications',
  'how-do-i-export-my-data':                                                       'q_exportData',
  'how-do-i-reset-my-data-and-start-fresh':                                       'q_resetData',
  'can-i-connect-yfit-to-other-health-apps':                                      'q_connectOtherApps',
  'what-happens-to-my-data-if-i-uninstall-the-app':                              'q_dataAfterUninstall',
  'how-do-i-contact-support':                                                      'q_contactSupport',
  'how-do-i-update-my-display-name':                                               'q_updateDisplayName',
  'how-do-i-manage-my-privacy-settings':                                           'q_managePrivacy',
  'how-do-i-update-my-profile-photo':                                              'q_updateProfilePhoto',
  'what-subscription-plans-does-yfit-offer':                                      'q_subscriptionPlans',
  'how-do-i-upgrade-to-pro':                                                       'q_upgradeToPro',
  'how-do-i-cancel-my-subscription':                                               'q_cancelSubscription',
  'can-i-get-a-refund':                                                            'q_getRefund',
  'is-there-a-free-trial':                                                         'q_freeTrial',
  'what-happens-to-my-data-if-i-downgrade-to-free':                              'q_dataAfterDowngrade',
  'how-do-i-update-my-payment-method':                                             'q_updatePaymentMethod',
  'what-is-the-lifetime-plan':                                                     'q_lifetimePlan',
  'is-my-payment-information-secure':                                              'q_paymentSecure',
  'do-you-offer-student-or-family-discounts':                                     'q_discounts',
  'the-app-shows-a-spinning-loading-screen-and-will-not-open-wh':                'q_loadingScreen',
  'the-barcode-scanner-is-not-working-how-do-i-fix-it':                          'q_barcodeScannerNotWorking',
  'my-nutrition-data-is-not-saving-what-should-i-check':                         'q_nutritionDataNotSaving',
  'the-app-is-very-slow-how-can-i-speed-it-up':                                  'q_appVerySlow',
  'i-cannot-log-in-to-my-account-what-should-i-do':                              'q_cannotLogIn',
  'my-workout-history-has-disappeared-what-happened':                             'q_workoutHistoryDisappeared',
  'the-ai-coach-is-not-responding-what-should-i-do':                             'q_aiCoachNotResponding',
  'my-step-count-is-not-updating-how-do-i-fix-it':                               'q_stepCountNotUpdating',
  'how-do-i-report-a-bug':                                                         'q_reportBug',
  'the-app-updated-and-now-something-is-broken-what-should-i-do':               'q_appUpdatedBroken',
}
